//Action Types
export const SET_APP_STATE = "SET_APP_STATE";
export const CLEAR_APP_STATE = "CLEAR_APP_STATE";

export const REQUEST_TRENDINGS = "REQUEST_TRENDINGS";
export const RECEIVE_TRENDINGS = "RECEIVE_TRENDINGS";
export const CLEAR_GIFS = "CLEAR_GIFS";


export const REQUEST_SEARCH = "REQUEST_SEARCH";
export const RECEIVE_SEARCH = "RECEIVE_SEARCH";
